"""Generate a Markdown repository summary without changing human-authored audits."""

from __future__ import annotations

import csv
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "reports" / "generated" / "repository-summary.md"
POST_MANIFEST = ROOT / "docs" / "reorganization" / "PHASE-3-POST-MIGRATION-MANIFEST.csv"
CATEGORY_RE = re.compile(r"^(?:0[1-9]|1[0-6]|90)-")
FORBIDDEN_RE = re.compile(r"(?:^|[\s_.()\-])(v1|v2|final|new|claude[\s_-]+version|claude[\s_-]+code)(?:$|[\s_.()\-])", re.I)
LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)]+)\)")


def repository_files() -> list[Path]:
    """Return all non-Git files except the report being generated."""
    return sorted(
        path for path in ROOT.rglob("*")
        if path.is_file()
        and ".git" not in path.relative_to(ROOT).parts
        and "__pycache__" not in path.relative_to(ROOT).parts
        and path != OUTPUT
    )


def normalized(name: str) -> str:
    """Normalize a filename for candidate grouping."""
    stem = FORBIDDEN_RE.sub(" ", Path(name).stem.casefold().strip())
    return re.sub(r"[^a-z0-9]+", "", stem)


def duplicate_candidates(paths: list[Path]) -> list[list[Path]]:
    """Return same-normalized-name candidate groups."""
    groups: dict[str, list[Path]] = defaultdict(list)
    for path in paths:
        if path.name != "README.md":
            groups[normalized(path.name)].append(path)
    return [members for members in groups.values() if len(members) > 1]


def naming_violations(paths: list[Path]) -> list[Path]:
    """Return paths that violate one or more portable naming rules."""
    violations: list[Path] = []
    for path in paths:
        rel = path.relative_to(ROOT).as_posix()
        if " " in rel or "(" in rel or ")" in rel or "--" in rel or FORBIDDEN_RE.search(rel):
            violations.append(path)
    return violations


def broken_links(paths: list[Path]) -> list[str]:
    """Return missing local link targets using a conservative inline-link scan."""
    broken: list[str] = []
    for path in paths:
        if path.suffix.lower() != ".md":
            continue
        fenced = False
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if line.lstrip().startswith(("```", "~~~")):
                fenced = not fenced
                continue
            if fenced:
                continue
            for match in LINK_RE.finditer(line):
                raw = match.group(1).strip().strip("<>").split(maxsplit=1)[0]
                if not raw or raw.startswith(("http://", "https://", "mailto:", "data:")):
                    continue
                file_part = raw.partition("#")[0]
                target = path if not file_part else path.parent / file_part
                if target.is_dir():
                    continue
                if not target.exists():
                    broken.append(f"{path.relative_to(ROOT).as_posix()}:{number} -> {raw}")
    return broken


def main() -> int:
    """Create the generated summary and return a process exit code."""
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="backslashreplace")
    paths = repository_files()
    markdown = [path for path in paths if path.suffix.lower() == ".md"]
    top_counts = Counter(path.relative_to(ROOT).parts[0] for path in paths)
    categories = sorted(path.name for path in ROOT.iterdir() if path.is_dir() and CATEGORY_RE.match(path.name))
    foundation_roots = set(categories) | {"docs", "scripts", "reports"}
    root_foundation = {"README.md", "AGENTS.md", "CONTRIBUTING.md", ".gitattributes", ".gitignore", ".markdownlint.json"}
    legacy = [path for path in paths if path.relative_to(ROOT).parts[0] not in foundation_roots and path.name not in root_foundation]
    duplicates = duplicate_candidates(paths)
    broken = broken_links(paths)
    violations = naming_violations(paths)
    migration_text = "Foundation created; controlled file migration has not started. Legacy notes remain in place."
    if POST_MANIFEST.exists():
        with POST_MANIFEST.open(encoding="utf-8", newline="") as handle:
            migration_counts = Counter(row["migration_status"] for row in csv.DictReader(handle))
        migrated = migration_counts["migrated"]
        unresolved = sum(migration_counts.values()) - migrated
        migration_text = (
            f"Phase 3 controlled migration completed with **{migrated}** files moved and "
            f"**{unresolved}** unresolved files preserved in legacy locations. "
            "Content review and duplicate consolidation remain pending."
        )
    lines = [
        "# Generated Repository Summary", "", "Generated by `scripts/generate-repository-report.py`.", "",
        "## Counts", "", f"- Total files: **{len(paths)}**", f"- Markdown files: **{len(markdown)}**",
        f"- Legacy files remaining: **{len(legacy)}**", f"- Foundation categories created: **{len(categories)}**",
        f"- Duplicate filename candidate groups: **{len(duplicates)}**", f"- Broken local links: **{len(broken)}**",
        f"- Naming violations: **{len(violations)}**", "", "## Files by Top-Level Directory", "",
        "| Top-level path | Files |", "|---|---:|",
    ]
    lines.extend(f"| `{name}` | {count} |" for name, count in sorted(top_counts.items()))
    lines.extend(["", "## Migration Status", "", migration_text, ""])
    if duplicates:
        lines.extend(["## Duplicate Filename Candidates", ""])
        for members in duplicates:
            lines.append("- " + "; ".join(f"`{path.relative_to(ROOT).as_posix()}`" for path in members))
        lines.append("")
    if broken:
        lines.extend(["## Broken Local Links", ""] + [f"- `{item}`" for item in broken] + [""])
    if violations:
        lines.extend(["## Naming Violations", ""] + [f"- `{path.relative_to(ROOT).as_posix()}`" for path in violations] + [""])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT).as_posix()} with {len(paths)} file(s) summarized.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
